<?php

require_once __DIR__ . '/api_auth.php';

header("Access-Control-Allow-Origin: *");
header("Access-Control-Allow-Methods: POST, OPTIONS");
header("Access-Control-Allow-Headers: Content-Type, Authorization, x-api-key");
header("Content-Type: application/json");

error_reporting(E_ALL);
ini_set('display_errors', 1);

/*
|--------------------------------------------------------------------------
| Handle OPTIONS request
|--------------------------------------------------------------------------
*/

if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') {
    http_response_code(200);
    exit();
}

/*
|--------------------------------------------------------------------------
| Allow POST only
|--------------------------------------------------------------------------
*/

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    echo json_encode([
        "success" => false,
        "message" => "Only POST requests are allowed"
    ]);
    exit();
}

/*
|--------------------------------------------------------------------------
| Database connection
|--------------------------------------------------------------------------
*/

$conn = new mysqli(
    "localhost",
    "root",
    "",
    "salescollection"
);

if ($conn->connect_error) {
    echo json_encode([
        "success" => false,
        "message" => "Database connection failed: " . $conn->connect_error
    ]);
    exit();
}

$conn->set_charset("utf8mb4");

/*
|--------------------------------------------------------------------------
| Get JSON input
|--------------------------------------------------------------------------
*/

$rawInput = file_get_contents("php://input");

$data = json_decode($rawInput, true);

if (!$data || !is_array($data)) {
    echo json_encode([
        "success" => false,
        "message" => "Invalid JSON input"
    ]);
    $conn->close();
    exit();
}

/*
|--------------------------------------------------------------------------
| Get party details
|--------------------------------------------------------------------------
*/

$party_ledger_name       = trim($data["party_ledger_name"] ?? "");
$group_name              = trim($data["group_name"] ?? "");
$gst_registration_type   = trim($data["gst_registration_type"] ?? "");
$gstin                   = trim($data["gstin"] ?? "");
$mobile                  = trim($data["mobile"] ?? "");
$address                 = trim($data["address"] ?? "");
$email                   = trim($data["email"] ?? "");
$ledger_phone            = trim($data["ledger_phone"] ?? "");
$owner_name              = trim($data["owner_name"] ?? "");
$owner_phone             = trim($data["owner_phone"] ?? "");
$payment_contact_person  = trim($data["payment_contact_person"] ?? "");
$payment_contact_phone   = trim($data["payment_contact_phone"] ?? "");
$purchase_contact_person = trim($data["purchase_contact_person"] ?? "");
$purchase_contact_phone  = trim($data["purchase_contact_phone"] ?? "");
$field_executive         = trim($data["field_executive"] ?? "");
$requirement_type        = trim($data["requirement_type"] ?? "");
$decision_maker          = trim($data["decision_maker"] ?? "");
$referred_by             = trim($data["referred_by"] ?? "");

/*
|--------------------------------------------------------------------------
| Person who added the lead
|--------------------------------------------------------------------------
*/

$added_by = trim($data["added_by"] ?? "");

/*
|--------------------------------------------------------------------------
| Basic validation
|--------------------------------------------------------------------------
*/

if ($party_ledger_name === "") {
    echo json_encode([
        "success" => false,
        "message" => "Party name is required"
    ]);
    $conn->close();
    exit();
}

/*
|--------------------------------------------------------------------------
| Insert new party
|
| created_at is automatically generated by MySQL/MariaDB
| using NOW().
|--------------------------------------------------------------------------
*/

$sql = "INSERT INTO newpartyledgerdetails (
    party_ledger_name,
    group_name,
    gst_registration_type,
    gstin,
    mobile,
    address,
    email,
    ledger_phone,
    owner_name,
    owner_phone,
    payment_contact_person,
    payment_contact_phone,
    purchase_contact_person,
    purchase_contact_phone,
    field_executive,
    requirement_type,
    decision_maker,
    referred_by,
    added_by,
    created_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?, ?, ?, ?, ?, NOW()
)";

/*
|--------------------------------------------------------------------------
| Prepare statement
|--------------------------------------------------------------------------
*/

$stmt = $conn->prepare($sql);

if (!$stmt) {
    echo json_encode([
        "success" => false,
        "message" => "SQL prepare failed",
        "error" => $conn->error
    ]);
    $conn->close();
    exit();
}

/*
|--------------------------------------------------------------------------
| Bind parameters
|--------------------------------------------------------------------------
|
| 19 string parameters
| created_at uses NOW(), so it does not need a parameter.
|--------------------------------------------------------------------------
*/

$stmt->bind_param(
    "sssssssssssssssssss",
    $party_ledger_name,
    $group_name,
    $gst_registration_type,
    $gstin,
    $mobile,
    $address,
    $email,
    $ledger_phone,
    $owner_name,
    $owner_phone,
    $payment_contact_person,
    $payment_contact_phone,
    $purchase_contact_person,
    $purchase_contact_phone,
    $field_executive,
    $requirement_type,
    $decision_maker,
    $referred_by,
    $added_by
);

/*
|--------------------------------------------------------------------------
| Execute
|--------------------------------------------------------------------------
*/

if ($stmt->execute()) {

    $inserted_id = $stmt->insert_id;

    /*
    |--------------------------------------------------------------------------
    | Get the exact creation timestamp that was saved
    |--------------------------------------------------------------------------
    */

    $dateQuery = $conn->prepare("
        SELECT created_at
        FROM newpartyledgerdetails
        WHERE id = ?
        LIMIT 1
    ");

    $created_at = null;

    if ($dateQuery) {

        $dateQuery->bind_param("i", $inserted_id);
        $dateQuery->execute();

        $dateResult = $dateQuery->get_result();

        if ($dateRow = $dateResult->fetch_assoc()) {
            $created_at = $dateRow["created_at"];
        }

        $dateQuery->close();
    }

    /*
    |--------------------------------------------------------------------------
    | Success response
    |--------------------------------------------------------------------------
    */

    echo json_encode([
        "success" => true,
        "message" => "Party saved successfully",
        "id" => $inserted_id,
        "added_by" => $added_by,
        "created_at" => $created_at
    ]);

} else {

    /*
    |--------------------------------------------------------------------------
    | Insert failed
    |--------------------------------------------------------------------------
    */

    echo json_encode([
        "success" => false,
        "message" => "Insert failed",
        "error" => $stmt->error
    ]);
}

/*
|--------------------------------------------------------------------------
| Close
|--------------------------------------------------------------------------
*/

$stmt->close();
$conn->close();

?>